layout_spectrum: 0.4545990691985935
typography_spectrum: 0.2637104063760489
color:
  brandStrength: 0.6792018697597086
  lightness: 0.03445684211328626
  saturation: 0.39871828467585146
  rhythmicContrast: 0.7896928826812655
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: SKÝ FÓLK
